import { CalculatorRegistry } from './calculator-registry';
import { percentageCalculatorDef } from '../definitions/percentage';
import { discountCalculatorDef } from '../definitions/discount';
import { increaseCalculatorDef } from '../definitions/increase';
import { ratioCalculatorDef } from '../definitions/ratio';
import { vatCalculatorDef } from '../definitions/vat';
import { simpleInterestCalculatorDef } from '../definitions/simpleInterest';
import { compoundInterestCalculatorDef } from '../definitions/compoundInterest';
import { asalCarpanCalculatorDef } from '../definitions/asalCarpan';
import { ebobEkokCalculatorDef } from '../definitions/ebobEkok';
import { incCalculatorDef } from '../definitions/inc';
import { kokluSayiCalculatorDef } from '../definitions/kokluSayi';
import { metrekareCalculatorDef } from '../definitions/metrekare';
import { milCalculatorDef } from '../definitions/mil';
import { modulerAritmetikCalculatorDef } from '../definitions/modulerAritmetik';
import { oranCalculatorDef } from '../definitions/oran';
import { profitCalculatorDef } from '../definitions/profit';
import { lossCalculatorDef } from '../definitions/loss';
import { areaCalculatorDef } from '../definitions/area';
import { averageCostCalculatorDef } from '../definitions/averageCost';
import { volumeCalculatorDef } from '../definitions/volume';
import { perimeterCalculatorDef } from '../definitions/perimeter';
import { areaGeometryCalculatorDef } from '../definitions/areaGeometry';
import { factorialCalculatorDef } from '../definitions/factorial';
import { permutationCalculatorDef } from '../definitions/permutation';
import { combinationCalculatorDef } from '../definitions/combination';
import { ageCalculatorDef } from '../definitions/age';
import { consumerLoanCalculatorDef } from '../definitions/consumerLoan';
import { workplaceLoanCalculatorDef } from '../definitions/workplaceLoan';
import { mortgageLoanCalculatorDef } from '../definitions/mortgageLoan';
import { loanCalculatorDef } from '../definitions/loan';
import { loanFeeCalculatorDef } from '../definitions/loanFee';
import { loanEarlyPayoffPenaltyCalculatorDef } from '../definitions/loanEarlyPayoffPenalty';
import { loanLateFeeCalculatorDef } from '../definitions/loanLateFee';
import { creditCardMinimumPaymentCalculatorDef } from '../definitions/creditCardMinimumPayment';
import { creditCardAdditionalInstallmentCalculatorDef } from '../definitions/creditCardAdditionalInstallment';
import { creditCardLateFeeCalculatorDef } from '../definitions/creditCardLateFee';
import { creditCardInstallmentCalculatorDef } from '../definitions/creditCardInstallment';
import { creditCardCashAdvanceCalculatorDef } from '../definitions/creditCardCashAdvance';
import { loanRestructuringCalculatorDef } from '../definitions/loanRestructuring';
import { loanAnnualCostRateCalculatorDef } from '../definitions/loanAnnualCostRate';
import { maxLoanAmountCalculatorDef } from '../definitions/maxLoanAmount';
import { vehicleLoanCalculatorDef } from '../definitions/vehicleLoan';
import { commercialVehicleLoanCalculatorDef } from '../definitions/commercialVehicleLoan';
import { commercialConsumerLoanCalculatorDef } from '../definitions/commercialConsumerLoan';
import { commercialLoanCalculatorDef } from '../definitions/commercialLoan';
import { goldCalculatorDef } from '../definitions/gold';
import { compoundGrowthCalculatorDef } from '../definitions/compoundGrowth';
import { savingsCalculatorDef } from '../definitions/savings';
import { bondCalculatorDef } from '../definitions/bond';
import { currencyCalculatorDef } from '../definitions/currency';
import { inflationCalculatorDef } from '../definitions/inflation';
import { eurobondCalculatorDef } from '../definitions/eurobond';
import { interestCalculatorDef } from '../definitions/interest';
import { historicalGoldCalculatorDef } from '../definitions/historicalGold';
import { historicalCurrencyCalculatorDef } from '../definitions/historicalCurrency';
import { ibanValidationCalculatorDef } from '../definitions/ibanValidation';
import { financialDiscountCalculatorDef } from '../definitions/financialDiscount';
import { irrCalculatorDef } from '../definitions/irr';
import { rentIncreaseCalculatorDef } from '../definitions/rentIncrease';
import { npvCalculatorDef } from '../definitions/npv';
import { averageMaturityCalculatorDef } from '../definitions/averageMaturity';
import { monetaryValueCalculatorDef } from '../definitions/monetaryValue';
import { realReturnCalculatorDef } from '../definitions/realReturn';
import { repoCalculatorDef } from '../definitions/repo';
import { capitalDividendCalculatorDef } from '../definitions/capitalDividend';
import { tahvilCalculatorDef } from '../definitions/tahvil';
import { futuresPriceCalculatorDef } from '../definitions/futuresPrice';
import { timeDepositCalculatorDef } from '../definitions/timeDeposit';
import { agsCalculatorDef } from '../definitions/ags';
import { aksCalculatorDef } from '../definitions/aks';
import { alesCalculatorDef } from '../definitions/ales';
import { dgsCalculatorDef } from '../definitions/dgs';
import { dgsBaseScoresCalculatorDef } from '../definitions/dgsBaseScores';
import { dibMbstsCalculatorDef } from '../definitions/dibMbsts';
import { dusCalculatorDef } from '../definitions/dus';
import { ehliyetSinaviCalculatorDef } from '../definitions/ehliyetSinavi';
import { ekpssCalculatorDef } from '../definitions/ekpss';
import { eusCalculatorDef } from '../definitions/eus';
import { hakimSavcıYardımcılığıCalculatorDef } from '../definitions/hakimSavcıYardımcılığı';
import { hmgsCalculatorDef } from '../definitions/hmgs';
import { isgCalculatorDef } from '../definitions/isg';
import { iyosCalculatorDef } from '../definitions/iyos';
import { kpssCalculatorDef } from '../definitions/kpss';
import { lgsCalculatorDef } from '../definitions/lgs';
import { liseLgsTabanPuanlariCalculatorDef } from '../definitions/liseLgsTabanPuanlari';
import { msuCalculatorDef } from '../definitions/msu';
import { obpCalculatorDef } from '../definitions/obp';
import { oypCalculatorDef } from '../definitions/oyp';
import { ozelGuvenlikCalculatorDef } from '../definitions/ozelGuvenlik';
import { pmyoCalculatorDef } from '../definitions/pmyo';
import { pomemCalculatorDef } from '../definitions/pomem';
import { pybsCalculatorDef } from '../definitions/pybs';
import { tusCalculatorDef } from '../definitions/tus';
import { tytCalculatorDef } from '../definitions/tyt';
import { universiteYksTabanPuanlariDef } from '../definitions/universityBaseScores';
import { ydsCalculatorDef } from '../definitions/yds';
import { ydusCalculatorDef } from '../definitions/ydus';
import { yksCalculatorDef } from '../definitions/yks';
import { dersNotuCalculatorDef } from '../definitions/dersNotu';
import { eOkulNotCalculatorDef } from '../definitions/eOkul';
import { liseDersPuaniCalculatorDef } from '../definitions/liseDersPuani';
import { liseMezuniyetPuaniCalculatorDef } from '../definitions/liseMezuniyetPuani';
import { liseOrtalamaCalculatorDef } from '../definitions/liseOrtalama';
import { liseSinifGecmeCalculatorDef } from '../definitions/liseSinifGecme';
import { liseYbpCalculatorDef } from '../definitions/liseYbp';
import { okulaBaslamaYasiCalculatorDef } from '../definitions/okulaBaslamaYasi';
import { takdirTesekkurCalculatorDef } from '../definitions/takdirTesekkur';
import { universiteNotOrtalamasiCalculatorDef } from '../definitions/universiteNotOrtalamasi';
import { adetGunuCalculatorDef } from '../definitions/adetGunu';
import { asiTakvimiCalculatorDef } from '../definitions/asiTakvimi';
import { bazalMetabolizmaHiziCalculatorDef } from '../definitions/bmr';
import { bebekBoyuCalculatorDef } from '../definitions/bebekBoyu';
import { bebekKilosuCalculatorDef } from '../definitions/bebekKilosu';
import { belKalcaOraniCalculatorDef } from '../definitions/belKalcaOrani';
import { dogumTarihiCalculatorDef } from '../definitions/dogumTarihi';
import { gebelikCalculatorDef } from '../definitions/gebelik';
import { gunlukKaloriIhtiyaciCalculatorDef } from '../definitions/kaloriIhtiyaci';
import { gunlukKarbonhidratIhtiyaciCalculatorDef } from '../definitions/karbonhidratIhtiyaci';
import { gunlukKreatinDozuCalculatorDef } from '../definitions/kreatinDozu';
import { gunlukMakroBesinIhtiyaciCalculatorDef } from '../definitions/makroBesin';
import { gunlukProteinIhtiyaciCalculatorDef } from '../definitions/proteinIhtiyaci';
import { gunlukSuIhtiyaciCalculatorDef } from '../definitions/suIhtiyaci';
import { gunlukYagIhtiyaciCalculatorDef } from '../definitions/yagIhtiyaci';
import { idealKiloCalculatorDef } from '../definitions/idealKilo';
import { sigaraMaliyetiCalculatorDef } from '../definitions/sigaraMaliyeti';
import { sutyenBedeniCalculatorDef } from '../definitions/sutyenBedeni';
import { vkiCalculatorDef } from '../definitions/vki';
import { vucutYagOraniCalculatorDef } from '../definitions/vucutYagOrani';
import { yasamSuresiCalculatorDef } from '../definitions/yasamSuresi';
import { yumurtlamaDonemiCalculatorDef } from '../definitions/yumurtlamaDonemi';
import { alanCalculatorDef } from '../definitions/alan';
import { altinOranCalculatorDef } from '../definitions/altinOran';

/**
 * Bootstraps the Calculator Registry by loading all available calculators.
 * This should be called once, typically during app initialization or in the API route.
 */
let initialized = false;

export function initializeCalculators() {
  if (initialized) return;
  CalculatorRegistry.clear();
  CalculatorRegistry.register(percentageCalculatorDef);
  CalculatorRegistry.register(discountCalculatorDef);
  CalculatorRegistry.register(increaseCalculatorDef);
  CalculatorRegistry.register(ratioCalculatorDef);
  CalculatorRegistry.register(vatCalculatorDef);
  CalculatorRegistry.register(simpleInterestCalculatorDef);
  CalculatorRegistry.register(compoundInterestCalculatorDef);
  CalculatorRegistry.register(asalCarpanCalculatorDef);
  CalculatorRegistry.register(ebobEkokCalculatorDef);
  CalculatorRegistry.register(incCalculatorDef);
  CalculatorRegistry.register(kokluSayiCalculatorDef);
  CalculatorRegistry.register(metrekareCalculatorDef);
  CalculatorRegistry.register(milCalculatorDef);
  CalculatorRegistry.register(modulerAritmetikCalculatorDef);
  CalculatorRegistry.register(oranCalculatorDef);
  CalculatorRegistry.register(profitCalculatorDef);
  CalculatorRegistry.register(lossCalculatorDef);
  CalculatorRegistry.register(areaCalculatorDef);
  CalculatorRegistry.register(averageCostCalculatorDef);
  CalculatorRegistry.register(volumeCalculatorDef);
  CalculatorRegistry.register(perimeterCalculatorDef);
  CalculatorRegistry.register(areaGeometryCalculatorDef);
  CalculatorRegistry.register(factorialCalculatorDef);
  CalculatorRegistry.register(permutationCalculatorDef);
  CalculatorRegistry.register(combinationCalculatorDef);
  CalculatorRegistry.register(ageCalculatorDef);
  CalculatorRegistry.register(consumerLoanCalculatorDef);
  CalculatorRegistry.register(workplaceLoanCalculatorDef);
  CalculatorRegistry.register(mortgageLoanCalculatorDef);
  CalculatorRegistry.register(loanCalculatorDef);
  CalculatorRegistry.register(loanFeeCalculatorDef);
  CalculatorRegistry.register(loanEarlyPayoffPenaltyCalculatorDef);
  CalculatorRegistry.register(loanLateFeeCalculatorDef);
  CalculatorRegistry.register(creditCardMinimumPaymentCalculatorDef);
  CalculatorRegistry.register(creditCardAdditionalInstallmentCalculatorDef);
  CalculatorRegistry.register(creditCardLateFeeCalculatorDef);
  CalculatorRegistry.register(creditCardInstallmentCalculatorDef);
  CalculatorRegistry.register(creditCardCashAdvanceCalculatorDef);
  CalculatorRegistry.register(loanRestructuringCalculatorDef);
  CalculatorRegistry.register(loanAnnualCostRateCalculatorDef);
  CalculatorRegistry.register(maxLoanAmountCalculatorDef);
  CalculatorRegistry.register(vehicleLoanCalculatorDef);
  CalculatorRegistry.register(commercialVehicleLoanCalculatorDef);
  CalculatorRegistry.register(commercialConsumerLoanCalculatorDef);
  CalculatorRegistry.register(commercialLoanCalculatorDef);
  CalculatorRegistry.register(goldCalculatorDef);
  CalculatorRegistry.register(compoundGrowthCalculatorDef);
  CalculatorRegistry.register(savingsCalculatorDef);
  CalculatorRegistry.register(bondCalculatorDef);
  CalculatorRegistry.register(currencyCalculatorDef);
  CalculatorRegistry.register(inflationCalculatorDef);
  CalculatorRegistry.register(eurobondCalculatorDef);
  CalculatorRegistry.register(interestCalculatorDef);
  CalculatorRegistry.register(historicalGoldCalculatorDef);
  CalculatorRegistry.register(historicalCurrencyCalculatorDef);
  CalculatorRegistry.register(ibanValidationCalculatorDef);
  CalculatorRegistry.register(financialDiscountCalculatorDef);
  CalculatorRegistry.register(irrCalculatorDef);
  CalculatorRegistry.register(rentIncreaseCalculatorDef);
  CalculatorRegistry.register(npvCalculatorDef);
  CalculatorRegistry.register(averageMaturityCalculatorDef);
  CalculatorRegistry.register(monetaryValueCalculatorDef);
  CalculatorRegistry.register(realReturnCalculatorDef);
  CalculatorRegistry.register(repoCalculatorDef);
  CalculatorRegistry.register(capitalDividendCalculatorDef);
  CalculatorRegistry.register(tahvilCalculatorDef);
  CalculatorRegistry.register(futuresPriceCalculatorDef);
  CalculatorRegistry.register(timeDepositCalculatorDef);
  CalculatorRegistry.register(agsCalculatorDef);
  CalculatorRegistry.register(aksCalculatorDef);
  CalculatorRegistry.register(alesCalculatorDef);
  CalculatorRegistry.register(dgsCalculatorDef);
  CalculatorRegistry.register(dgsBaseScoresCalculatorDef);
  CalculatorRegistry.register(dibMbstsCalculatorDef);
  CalculatorRegistry.register(dusCalculatorDef);
  CalculatorRegistry.register(ehliyetSinaviCalculatorDef);
  CalculatorRegistry.register(ekpssCalculatorDef);
  CalculatorRegistry.register(eusCalculatorDef);
  CalculatorRegistry.register(hakimSavcıYardımcılığıCalculatorDef);
  CalculatorRegistry.register(hmgsCalculatorDef);
  CalculatorRegistry.register(isgCalculatorDef);
  CalculatorRegistry.register(iyosCalculatorDef);
  CalculatorRegistry.register(kpssCalculatorDef);
  CalculatorRegistry.register(lgsCalculatorDef);
  CalculatorRegistry.register(liseLgsTabanPuanlariCalculatorDef);
  CalculatorRegistry.register(msuCalculatorDef);
  CalculatorRegistry.register(obpCalculatorDef);
  CalculatorRegistry.register(oypCalculatorDef);
  CalculatorRegistry.register(ozelGuvenlikCalculatorDef);
  CalculatorRegistry.register(pmyoCalculatorDef);
  CalculatorRegistry.register(pomemCalculatorDef);
  CalculatorRegistry.register(pybsCalculatorDef);
  CalculatorRegistry.register(tusCalculatorDef);
  CalculatorRegistry.register(tytCalculatorDef);
  CalculatorRegistry.register(universiteYksTabanPuanlariDef);
  CalculatorRegistry.register(ydsCalculatorDef);
  CalculatorRegistry.register(ydusCalculatorDef);
  CalculatorRegistry.register(yksCalculatorDef);
  CalculatorRegistry.register(dersNotuCalculatorDef);
  CalculatorRegistry.register(eOkulNotCalculatorDef);
  CalculatorRegistry.register(liseDersPuaniCalculatorDef);
  CalculatorRegistry.register(liseMezuniyetPuaniCalculatorDef);
  CalculatorRegistry.register(liseOrtalamaCalculatorDef);
  CalculatorRegistry.register(liseSinifGecmeCalculatorDef);
  CalculatorRegistry.register(liseYbpCalculatorDef);
  CalculatorRegistry.register(okulaBaslamaYasiCalculatorDef);
  CalculatorRegistry.register(takdirTesekkurCalculatorDef);
  CalculatorRegistry.register(universiteNotOrtalamasiCalculatorDef);
  CalculatorRegistry.register(adetGunuCalculatorDef);
  CalculatorRegistry.register(asiTakvimiCalculatorDef);
  CalculatorRegistry.register(bazalMetabolizmaHiziCalculatorDef);
  CalculatorRegistry.register(bebekBoyuCalculatorDef);
  CalculatorRegistry.register(bebekKilosuCalculatorDef);
  CalculatorRegistry.register(belKalcaOraniCalculatorDef);
  CalculatorRegistry.register(dogumTarihiCalculatorDef);
  CalculatorRegistry.register(gebelikCalculatorDef);
  CalculatorRegistry.register(gunlukKaloriIhtiyaciCalculatorDef);
  CalculatorRegistry.register(gunlukKarbonhidratIhtiyaciCalculatorDef);
  CalculatorRegistry.register(gunlukKreatinDozuCalculatorDef);
  CalculatorRegistry.register(gunlukMakroBesinIhtiyaciCalculatorDef);
  CalculatorRegistry.register(gunlukProteinIhtiyaciCalculatorDef);
  CalculatorRegistry.register(gunlukSuIhtiyaciCalculatorDef);
  CalculatorRegistry.register(gunlukYagIhtiyaciCalculatorDef);
  CalculatorRegistry.register(idealKiloCalculatorDef);
  CalculatorRegistry.register(sigaraMaliyetiCalculatorDef);
  CalculatorRegistry.register(sutyenBedeniCalculatorDef);
  CalculatorRegistry.register(vkiCalculatorDef);
  CalculatorRegistry.register(vucutYagOraniCalculatorDef);
  CalculatorRegistry.register(yasamSuresiCalculatorDef);
  CalculatorRegistry.register(yumurtlamaDonemiCalculatorDef);
  CalculatorRegistry.register(alanCalculatorDef);
  CalculatorRegistry.register(altinOranCalculatorDef);
  initialized = true;
}

// Auto-initialize for seamless usage
initializeCalculators();

